# Generated by Django 4.2.2 on 2023-06-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booknow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('country_zip', models.CharField(max_length=122)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('rooms', models.IntegerField(max_length=3)),
                ('adults', models.IntegerField(max_length=3)),
                ('children', models.IntegerField(max_length=2)),
                ('email', models.EmailField(max_length=122)),
                ('phonenumber', models.CharField(max_length=15)),
            ],
        ),
    ]
