# Generated by Django 4.2.2 on 2023-06-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelHive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='adults',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='children',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
