# Generated by Django 4.2.2 on 2023-06-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostelHive', '0003_alter_booknow_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booknow',
            name='adults',
        ),
    ]
