# Generated by Django 4.2.2 on 2023-06-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelHive', '0007_alter_booknow_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='adults',
            field=models.CharField(default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='children',
            field=models.CharField(default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='email',
            field=models.EmailField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='rooms',
            field=models.CharField(default=1, max_length=15),
        ),
    ]
