# Generated by Django 4.2.2 on 2023-06-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelHive', '0008_alter_booknow_adults_alter_booknow_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='adults',
            field=models.CharField(default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='children',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='rooms',
            field=models.CharField(default='1', max_length=15),
        ),
    ]
